### PR TITLE
Documentation on DStidy dataset

### PR DESCRIPTION
**Pull request by janithwanni**
Dear Madam, 
I made the requested documentation for the DStidy dataset. 
I also added some documentation to DSraw dataset as well but I could not figure out what the final columns meant.

### CODE REVIEW

**Comment by thiyangt** [comment]
Thank you very much for the contribution. One point to clarify, do you mean the last column in the DSraw?

**Comment by thiyangt** [comment]
Few more issues to fix. I am getting this warning message when building the package

checking for code/documentation mismatches ... WARNING
  Data codoc mismatches from documentation object 'DSraw':
  Variables in data frame 'DSraw'
    Code: AI AWS Alteryx Bahasa Malaysia Bash Bash\Linux Scripting
          Bayesian BigData C C# C++ City Communication Company
          Computer_vision Consultant Content_Management D3 Data_Pipelines
          Data_management Data_marketing Data_mining Data_science
          Data_visualization Data_warehouse DatePublished DateRetrieved
          Debtor_reconcilation Deep Learning DigitalOcean Economic
          Educational_qualifications Elasticsearch English proficiency
          Experience Finance_Knowledge Flash_Actionscript
          Google_Analytics Google_Cloud Hadoop Hive ID IOT Impala
          Investment_Knowledge Java Javascript Job_title KNIME Kafka
          Knowledge_in Korean_language Linux/Unix Location MAtlab
          MPP_Platforms MS Word Machine_Learning Map/Reduce Microsoft
          Power BI MongoDB Ms Access Ms Excel Ms PowerPoint MySQL
          Natural_Language_Processing(NLP) NoSQL Numerical_Analysis
          OLE/DB Optimization Oracle PHP Payroll_management Pig
          Presentation_Skills Problem_Solving Python Qlik R RDBMS
          Redshift S3 SAS SEO SPL SPSS SQL Salary Scala Search_Term Solr
          Spark Spotfire Spreadsheets Storm Tableau Team_Handling
          Tensorflow Teradata URL Web_Analytic_tools Wordpress X109 X110
          X111 X112 X113 X114 X115 X116 X117 X118 X119 X120 X121 X122
          X123 X124 X125 X126 X127 X128 X129 X130 X131 X132 X133 X134
          X135 X136 X137 X138 X139 X140 X141 X142 X143 X144 X145 X146
          X147 X148 X149 X150 X151 X152 YOLO agile execution
          cloud_storage graphics_and_design_skills pyspark
          web_design_and_development_tools
    Docs: AI AWS Alteryx Bahasa Malaysia Bash Bash\ Linux_Scripting
          Bayesian BigData C C_Sharp City Communication Company
          Computer_vision Consultant Content_Management Cpp D3
          DataRetrieved Data_Management Data_Pipelines Data_Science
          Data_marketing Data_mining Data_visualization Data_warehouse
          DatePublished Debtor_reconciliation Deep_Learning DigitalOcean
          Economic Educational_qualifications Elasticsearch English
          proficiency Experience Finance_Knowledge Flash_Actionscript
          Google_Analytics Google_Cloud Hadoop Hive ID IOT Impala
          Investment_Knowledge Java Javascript Job_title KNIME Kafka
          Knowledge_in Korean_language Linux_Unix Location MAtlab
          MPP_Platforms MS_Word Machine_Learning Map_Reduce
          Microsoft_Power_BI MongoDB Ms_Access Ms_Excel Ms_PowerPoint
          MySQL Natural_Language_Processing(NLP) NoSQL Numerical_Analysis
          OLE_DB Optimization Oracle PHP Payroll_management Pig
          Presentation_Skills Problem_Solving Python Qlik R RDBMS
          Redshift S3 SAS SEO SPL SPSS SQL Salary Scala Search_Term Solr
          Spark Spotfire Spreadsheets Storm Tableau Team_Handling
          Tensorflow Teradata URL Web_Analytic_tools Wordpress YOLO agile
          execution cloud_storage graphics_and_design_skills pyspark
          web_design_and_development_tools
  
  Data codoc mismatches from documentation object 'DStidy':
  Variables in data frame 'DStidy'
    Code: AI AWS Alteryx Bahasa_Malaysia Bash Bash_Linux_Scripting
          Bayesian BigData C C. C.. City Communication Company
          Computer_vision Consultant Content_Management D3 Data_Pipelines
          Data_management Data_marketing Data_mining Data_science
          Data_visualization Data_warehouse DatePublished DateRetrieved
          Debtor_reconcilation Deep_Learning DigitalOcean Economic
          Edu_Category Educational_qualifications Elasticsearch
          English_proficiency Experience Experience_Category
          Finance_Knowledge Flash_Actionscript Google_Analytics
          Google_Cloud Hadoop Hive ID IOT Impala Investment_Knowledge
          Java Javascript Job_Category Job_Country Job_Titles Job_title
          KNIME Kafka Knowledge_in Korean_language Linux_Unix Location
          MAtlab MPP_Platforms MS_Word Machine_Learning Map_Reduce
          Microsoft_Power_BI Minimum_Years_of_experience MongoDB
          Ms_Access Ms_Excel Ms_PowerPoint MySQL
          Natural_Language_Processing.NLP. NoSQL Numerical_Analysis
          OLE_DB Optimization Oracle PHP Payroll_management Pig
          Presentation_Skills Problem_Solving Python Qlik R RDBMS
          Redshift S3 SAS SEO SPL SPSS SQL Salary Scala Search_Term Solr
          Spark Spotfire Spreadsheets Storm Tableau Team_Handling
          Tensorflow Teradata URL Web_Analytic_tools Wordpress YOLO
          agile_execution cloud_storage graphics_and_design_skills
          pyspark web_design_and_development_tools
    Docs: AI AWS Alteryx Bahasa_Malaysia Bash Bash_Linux_Scripting
          Bayesian BigData C C_Sharp City Communication Company
          Computer_vision Consultant Content_Management Cpp D3
          DataRetrieved Data_Management Data_Pipelines Data_Science
          Data_marketing Data_mining Data_visualization Data_warehouse
          DatePublished Debtor_reconciliation Deep_Learning DigitalOcean
          Economic Edu_Category Educational_qualifications Elasticsearch
          English_proficiency Experience Experience_Category
          Finance_Knowledge Flash_Actionscript Google_Analytics
          Google_Cloud Hadoop Hive ID IOT Impala Investment_Knowledge
          Java Javascript Job_Category Job_Country Job_title KNIME Kafka
          Knowledge_in Korean_language Linux_Unix Location MAtlab
          MPP_Platforms MS_Word Machine_Learning Map_Reduce
          Microsoft_Power_BI Minimum_Salary Minimum_Years_of_experience
          MongoDB Ms_Access Ms_Excel Ms_PowerPoint MySQL
          Natural_Language_Processing(NLP) NoSQL Numerical_Analysis
          OLE_DB Optimization Oracle PHP Payroll_management Pig
          Presentation_Skills Problem_Solving Python Qlik R RDBMS
          Redshift S3 SAS SEO SPL SPSS SQL Salary Salary_Basis Scala
          Search_Term Solr Spark Spotfire Spreadsheets Storm Tableau
          Team_Handling Tensorflow Teradata URL Web_Analytic_tools
          Wordpress YOLO agile execution cloud_storage
          graphics_and_design_skills pyspark
          web_design_and_development_tools

**Comment by janithwanni** [comment]
> Thank you very much for the contribution. One point to clarify, do you mean the last column in the DSraw?

Yes the X109 to X152 variables. I believe most of them have NAs as well

**Comment by thiyangt** [comment]
Yes you are correct!

**Pull request merged**
